### PR TITLE
[25] [Backend] Create survey info

### PR DESCRIPTION
**Pull request by markgravity**
https://github.com/markgravity/flutter-survey/issues/25

## What happened

Create Survey info to prepare for Home screen
 
## Proof Of Work

N/A

### CODE REVIEW

**Comment by manh-t** [comment]
@markgravity oh, just curious why do we only have 1 data class here? I don't see its usage 😅

**Comment by manh-t** [comment]
@markgravity ah sorry, I see it its usage in #81

**Comment by sleepylee** [comment]
actually, defining the API endpoint, configure request type, request params are related to the [Backend] ticket/PR, @markgravity FYI. 
The current one is a part of mapping the response, you will need the part to make the request and response before that as well right?

**Comment by markgravity** [comment]
> actually, [defining the API endpoint, configure request type, request params ](https://github.com/markgravity/flutter-survey/pull/81/files#diff-4ef1a028ec8397cee6a6f794861738feba3b7d6ed81888c1b4450754692d65db)are related to the [Backend] ticket/PR, @markgravity FYI.
> The current one is a part of mapping the response, you will need the part to make the request and response before that as well right?

Don't get your mean there? You mean that this PR should be added into Fetch Survey [PR](https://github.com/markgravity/flutter-survey/pull/81/files#diff-4ef1a028ec8397cee6a6f794861738feba3b7d6ed81888c1b4450754692d65db)?

**Comment by sleepylee** [comment]
yes @markgravity they can stay together. If you come back to #81 and remove all the non-related to [Backend] ticket i.e: [UI] implementation, you will see these pieces are related to the backend interaction we are trying to fetch the data from the API

**Comment by manh-t** [comment]
@markgravity seems you create duplicate [survey_info.dart](https://github.com/markgravity/flutter-survey/blob/f8a70e884d2a111db9f267533ee299fed12749f3/lib/models/survey_info.dart) in #81 . Why do you create this PR? 😅

**Comment by markgravity** [comment]
> yes @markgravity they can stay together. If you come back to #81 and remove all the non-related to [Backend] ticket i.e: [UI] implementation, you will see these pieces are related to the backend interaction we are trying to fetch the data from the API

So because in UI ticket, I need `SurveyInfo`, so that why I created them follow
Create Survey Info -> UI -> BE -> Integrate

**Comment by sleepylee** [comment]
😂  normally in the [UI] ticket, you should just display the mock/hardcoded data. So when we fetch everything, we start making the reactive stream with [Integrate] ticket, that's where it won't messing between different domains.

**Comment by markgravity** [comment]
> 😂 normally in the [UI] ticket, you should just display the mock/hardcoded data. So when we fetch everything, we start making the reactive stream with [Integrate] ticket, that's where it won't messing between different domains.

Yea, one thing have learned there 😁

**Comment by sleepylee** [comment]
or you do the [Backend] ticket first, before doing the [UI] ticket, this is my fav approach so I don't have to fake the data.

Otherwise, how do you explain why a [Backend] ticket #81 contains the UI code? 😄

**Comment by markgravity** [comment]
> or you do the [Backend] ticket first, before doing the [UI] ticket, this is my fav approach so I don't have to fake the data.
> 
> Otherwise, how do you explain why a [Backend] ticket #81 contains the UI code? 😄

It needs to rebase 😁

**Comment by sleepylee** [comment]
@markgravity perhaps just bring all the [Backend] related code to here, we can review and approve them, then #81 which you can turn into a [UI] only ticket, and target for your next sprint.

**Comment by markgravity** [comment]
> @markgravity perhaps just bring all the [Backend] related code to here, we can review and approve them, then #81 which you can turn into a [UI] only ticket, and target for your next sprint.

@sleepylee  updated. I will close this PR

**Pull request closed without merging**
